// <auto-generated />
using System;
using DataAccess.WallerAppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(WalletAppDbContext))]
    [Migration("20231101160928_ImproveSeed")]
    partial class ImproveSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.TransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64000)
                        .HasColumnType("character varying(64000)");

                    b.Property<bool>("IsAutorizedUser")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPending")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ct_transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 12.130000000000001,
                            Date = new DateTime(2023, 11, 1, 16, 9, 27, 988, DateTimeKind.Utc).AddTicks(22),
                            Description = "Some description 1",
                            IsAutorizedUser = true,
                            IsPending = true,
                            Name = "Transaction 1",
                            Type = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 12.15,
                            Date = new DateTime(2002, 12, 12, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 2",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 2",
                            Type = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1256.0,
                            Date = new DateTime(2002, 12, 12, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 3",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 3",
                            Type = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1256.0,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 4",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 4",
                            Type = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 456.0,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 5",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 5",
                            Type = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 189.91999999999999,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 6",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 6",
                            Type = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 189.91999999999999,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 7",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 7",
                            Type = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 189.91999999999999,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 8",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 8",
                            Type = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 189.91999999999999,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 8",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 9",
                            Type = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 189.91999999999999,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 10",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 10",
                            Type = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 12.130000000000001,
                            Date = new DateTime(2023, 11, 1, 16, 9, 27, 988, DateTimeKind.Utc).AddTicks(172),
                            Description = "Some description 1",
                            IsAutorizedUser = true,
                            IsPending = true,
                            Name = "Transaction 1",
                            Type = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            Amount = 12.15,
                            Date = new DateTime(2002, 12, 12, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 2",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 2",
                            Type = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            Amount = 1256.0,
                            Date = new DateTime(2002, 12, 12, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 3",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 3",
                            Type = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            Amount = 1256.0,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 4",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 4",
                            Type = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            Amount = 456.0,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 5",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 5",
                            Type = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            Amount = 189.91999999999999,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 6",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 6",
                            Type = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            Amount = 189.91999999999999,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 7",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 7",
                            Type = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 189.91999999999999,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 8",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 8",
                            Type = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 189.91999999999999,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 8",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 9",
                            Type = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            Amount = 189.91999999999999,
                            Date = new DateTime(2023, 11, 2, 12, 12, 12, 0, DateTimeKind.Unspecified),
                            Description = "Some description 10",
                            IsAutorizedUser = false,
                            IsPending = false,
                            Name = "Transaction 10",
                            Type = 0,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ct_users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User 2"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.TransactionEntity", b =>
                {
                    b.HasOne("DataAccess.Entities.UserEntity", "User")
                        .WithMany("Entities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Entities.UserEntity", b =>
                {
                    b.Navigation("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
